version: '2'
services:
  account:
    build: account/
    ports:
     - "8081:8080"
    environment:
      serviceUrl: "http://IP:PORT/account"
      registryUrl: "http://IP:PORT"
  balance:
    build: balance/
    ports:
     - "8082:8080"
    environment:
      serviceUrl: "http://IP:PORT/balance"
      registryUrl: "http://IP:PORT"