version: '2'
services:
  account:
    build: account/
    ports:
     - "8081:8080"
    environment:
      serviceUrl: "http://192.168.0.7:8081/account"
      registryUrl: "http://192.168.0.7:8080"
  balance:
    build: balance/
    ports:
     - "8082:8080"
    environment:
      serviceUrl: "http://192.168.0.7:8082/balance"
      registryUrl: "http://192.168.0.7:8080"